### ISSUE TITLE
Runtime Instalation Process

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-runtime-browser#36]
Hi @dvilchez,

I have tested the browser runtime, and it's working well, but I found a problem;

You have this const to load runtimeURL
```javascript
const runtimeURL = 'hyperty-catalogue://' + window.location.hostname + '/.well-known/runtime/RuntimeUA';
```

But the request need to be to the catalogue, by the way, you should put in your runtimeURL const, something like:
```javascript
const runtimeURL = 'hyperty-catalogue://catalogue.' + window.location.hostname + '/.well-known/runtime/RuntimeUA';
```

Another question is, the runtimeUA couldn't call runtimeUA, could be MyRuntime, or other, then that runtimeURL const should be dynamic. Probably you need to check the install parameter and verify if it is a domain or a URL.

**Comment by vitormsilva** [comment]
@dvilchez,

Other improve you need to do on runtime-browser, is related with the `catalogue.getRuntimeDescriptorURL()` in file [core.js](https://github.com/reTHINK-project/dev-runtime-browser/blob/master/src/core.js#L46)

Explaining:
When i did the the runtimeLoader, i was assuming the runtime descriptor bring the sourcePackage included on it self, but, seems not.

By the way, you need to add some more code, and optimize with something like this:

```javascript
catalogue.getRuntimeDescriptor(runtimeURL).then(function(descriptor) {

    let sourcePackageURL = descriptor.sourcePackageURL;
    if (sourcePackageURL === '/sourcePackage') {
        return descriptor.sourcePackage;
    }

    return catalogue.getSourcePackageFromURL(sourcePackageURL);
})
.then(function(sourcePackage) {
   console.log(sourcePackage);

   eval.apply(window,[sourcePackage.sourceCode])
   let runtime = new RuntimeUA(RuntimeFactory, window.location.hostname);
});
```

If you don't understant what i mean, you can check this [issue](https://github.com/reTHINK-project/dev-service-framework/issues/32#issuecomment-209849300)

**Comment by dvilchez** [comment]
@vitormsilva regarding pass the runtime url in the install call, could you give me some valid examples? I need some way to distinguis between a domain and a valid runtime-url.

**Comment by pchainho** [comment]
Domain example: "hybroker.rethink.ptinovacao.pt"

Full Runtime Catalogue URL example: "https://catalogue.hybroker.rethink.ptinovacao.pt/.well-known/runtime/myAwesomeRuntime"

**Comment by dvilchez** [comment]
@pchainho then we can use the protocol presence or absence to determine if it is a domain or a runtime URL, are you agree?

**Comment by pchainho** [comment]
I guess that's a valid criteria, yes, to check whether it is an URL by looking for the URL scheme in the string

**Comment by emmelmann-fokus** [comment]
Just keep in mind the extensibility:

We either have to check for the presence of any supported protocol (http, https, maybe more in the future), or we check for the following regular expression to match:  *//:*  

I do not know what is easier to implement vs. easier to maintain.

**Comment by dvilchez** [comment]
I pushed my changes to a new branch but I found a problem. If I do the installation, passing it my runtime-url (http://catalogue.rethink-app.quobis.com/.well-known/runtime/RuntimeUA), the domain  will be resolved to catalogue.rethink-app.quobis.com and application will fail because it won't be able to find any static resources there.

**Comment by pchainho** [comment]
You should take the info about the environment used as proposed [here](https://github.com/reTHINK-project/dev-runtime-core/issues/75#issuecomment-212022435) and change the Catalogue URL in case it is a "development" environment, since the Local Catalogue use different URLs: `'https://' + domain + '/resources/descriptores/Runtimes.json'`

**Comment by dvilchez** [comment]
Just to clarify @pchainho,

In dev mode, catalogue url -> 'https://' + domain + '/resources/descriptores/Runtimes.json'
In prod mode, catalogue url -> 'https://catalog.' + domain + '/resources/descriptores/Runtimes.json'

**Comment by pchainho** [comment]
You just have to change the catalogue URL in dev mode to: `'https://' + domain + '/resources/descriptores/Runtimes.json'`

No change of the catalogue URL is required in prod mode

**Comment by emmelmann-fokus** [comment]
I don't know if I need to object here.  But I definitely cannot (yet) agree:

> In dev mode, catalogue url -> 'https://' + domain + '/resources/descriptores/Runtimes.json'
> In prod mode, catalogue url -> 'https://catalog.' + domain + '/resources/descriptores/Runtimes.json'

These are constrains that have not been agreed on, not even discussed so far as it implies that the catalogue is always reachable in a production environment by contacting the host "catalog.DOMOAIN".

The implementation should not have that as a static code.

If we keep this constrain, we might run into serious implications for the testbed.  For example, IT policies at Fraunhofer do not permit us to create another level domain, i.e. rethink.fokus.fraunhofer.de as a domain will not be available, hence, catalogue.rethink.fokus.fraunhofer.de will *not* be available to contact a catalogue service.  I am not sure if we can provide a hostname "catalogue" within the fokus.fraunhofer.de domain.

**Comment by pchainho** [comment]
@emmelmann-fokus we have agreed a long time on this and you were the first one proposing this URL for the catalogue:

https://github.com/reTHINK-project/architecture/issues/63#issuecomment-152235722
