### ISSUE TITLE
Policy Engine Admin GUI

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-browser#37]
moved from https://github.com/reTHINK-project/dev-runtime-core/issues/64

As discussed [here](https://github.com/reTHINK-project/core-framework/issues/160)

**Comment by AnaSLCaldeira** [comment]
I developed a version that interacts with a fake Policy Engine. Now I need to integrate it on the reTHINK application, but I don't know where to place the files or how to load them to the application.

**Comment by pchainho** [comment]
why fake policy engine? As discussed [here](https://github.com/reTHINK-project/core-framework/issues/160) the Admin Pages should be inside the iFrame and they could directly invole the Policy Engine API. Then these pages would be unhidden/hidden according to messages sent to RuntimeUAStub outside the iFrame.

**Comment by AnaSLCaldeira** [comment]
I understand that this admin pages must be inside the iframe, I said fake as in simplified version to ease the development, as it does not interact with the remaining reTHINK submodules and runs locally. Where are these files to be placed? In the runtime-browser repository under src/admin? How do I expose them to the user in the reTHINK application?

**Comment by pchainho** [comment]
I now see issue #47 where probably we should move the discussion to this since this is also common to other componentes having GUI admin pages like the Id Module

**Comment by AnaSLCaldeira** [comment]
This was implemented and committed in the develop-gui branch. @vitormsilva @dvilchez @pchainho Please let me know if you find any trouble using it or if you have any suggestions for improvements.
