### ISSUE TITLE
Graph Connector Admin GUI

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-browser#38]
As discussed [here](https://github.com/reTHINK-project/core-framework/issues/160)

**Comment by pchainho** [comment]
see more details at #47 and https://github.com/reTHINK-project/core-framework/issues/160

**Comment by fbeierle** [comment]
Please see here for update: https://github.com/reTHINK-project/dev-runtime-core/issues/33#issuecomment-279719217
