### ISSUE TITLE
Identity Module Admin GUI 

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-browser#39]
As discussed [here](https://github.com/reTHINK-project/core-framework/issues/160)

**Comment by gamdias** [comment]
I'm having trouble to understand how to load an Identity GUI component that can use the message bus, with the reTHINK application from the dev-hyperty-toolkit.

Does anyone have any ideas?

Ideally, if someone could provide an "hello world" example of loaded GUI into the reTHINK application, with the message Bus I would appreciate it.
thanks! :)

**Comment by pchainho** [comment]
see #47 pls

**Comment by pchainho** [comment]
Done
