### ISSUE TITLE
TyperError: Cannot read property 'configuration' of undefined

### ISSUE THREAD

**Issue by fbeierle** [reTHINK-project/dev-runtime-browser#44]
I created a very simple example that posts a message to the iframe to call a method on the GraphConnector (https://github.com/reTHINK-project/dev-runtime-browser/tree/develop-GraphConnector).
I get this error:

![demo4](https://cloud.githubusercontent.com/assets/10813769/15078594/3b4829d0-13b4-11e6-8b81-592c9e95da41.png)

The example in dev-runtime-core (https://github.com/reTHINK-project/dev-runtime-core/tree/dev-0.5-GraphConnector/example) isn't running anymore as well, and returning the same error. The Google login windows does not pop up anymore. As the log output is not very specific I am unsure how to fix this. Is it possible that some changes in dev-service-framework are creating this error?

**Comment by fbeierle** [comment]
After merging the latest changes from master, I get this error and I am unsure where it comes from:

![demo5](https://cloud.githubusercontent.com/assets/10813769/15208600/ca9aac3a-182c-11e6-9243-f52974027adc.png)

@dvilchez : Can you help me here?

**Comment by dvilchez** [comment]
@fbeierle closed with 6708463e0423f2aa83f5bf569e53f82555b3c35f
