### ISSUE TITLE
GUI integration in the examples

### ISSUE THREAD

**Issue by AnaSLCaldeira** [reTHINK-project/dev-runtime-browser#47]
Could someone help us integrate the Policies and Identity GUI in the examples? In the policies-GUI branch, the HTML code is at dev-runtime-browser/example/.well-known/runtime/index.html, and the JavaScript is at dev-runtime-browser/src/admin/IdentitiesGUI.js and dev-runtime-browser/src/admin/PoliciesGUI.js.

Thank you, in advance!

**Comment by pchainho** [comment]
The proposal is to use these [message specs](https://github.com/reTHINK-project/dev-service-framework/blob/master/docs/specs/messages/identity-management-messages.md#hide--unhide-identity-module-admin-page) to ask rethink.js to unhide / hide the admin page. This would imply the rethink.js to have registered a listener at the msg bus at "hyperty-runtime://<runtime-domain>/<runtime-instance-identifier>/gui-manager" ; @dvilchez ?

**Comment by dvilchez** [comment]
@pchainho I am not sure the problem for @AnaSLCaldeira and @gamdias is how hide or unhide the iframe. I can do it but, in the current design, we only have a iframe where runtime-core is hosted, Are these GUIs inside this iframe?

**Comment by pchainho** [comment]
As discussed [here](https://github.com/reTHINK-project/core-framework/issues/160) the admin pages should be inside the iframe

**Comment by dvilchez** [comment]
@pchainho done in e691773c416fd528fe72f71396fac1334975820f

**Comment by pchainho** [comment]
@AnaSLCaldeira @gamdias can you have try? do you need any further support / help?

**Comment by AnaSLCaldeira** [comment]
How can I test my changes on core.js? When I do 'gulp bundle' and then copy the dev-runtime-browser/bin/core.js file to dev-hyperty-toolkit/node-modules/runtime-browser/bin, it shows this error:

Uncaught (in promise) TypeError: Illegal invocation(…)    RuntimeCatalogue.js:31

Am I doing something wrong?

**Comment by fbeierle** [comment]
I got an email about a post by @AnaSLCaldeira about getting an error when using runtime-browser:

<pre>Uncaught (in promise) TypeError: Illegal invocation(…) RuntimeCatalogue.js:31</pre>

As I am facing the same issue: @AnaSLCaldeira How did you solve this issue?

@gniewus @ishantiw

**Comment by AnaSLCaldeira** [comment]
@fbeierle I had that error and couldn't figure out its source, so I just restarted everything and the error disappeared. I didn't exactly solve it, that's why I deleted my comment. I'm sorry for not being able to provide a solution, maybe someone else had that error and figures it out?

**Comment by fbeierle** [comment]
Using the master branch of dev-service-framework (see https://github.com/reTHINK-project/dev-runtime-browser/blob/develop-GraphConnector-Test/package.json#L65), it works. So it seems that the changes made in the develop branch of service-framework are causing this error.

@reTHINK-project/wp3

**Comment by AnaSLCaldeira** [comment]
@pchainho @dvilchez thank you for your support, I have committed the implementation in the develop-gui branch.
