### ISSUE TITLE
ECPair error and TypeError: Cannot read property 'curve' of undefined

### ISSUE THREAD

**Issue by ishantiw** [reTHINK-project/dev-runtime-browser#48]
We created an example under `example` folder in https://github.com/reTHINK-project/dev-runtime-browser/blob/develop-GraphConnector-Test/example/guid.js. `generateGUID`[#L63 ](https://github.com/reTHINK-project/dev-runtime-browser/blob/develop-GraphConnector-Test/example/guid.js#L63)and `useGUID`[#L71](https://github.com/reTHINK-project/dev-runtime-browser/blob/develop-GraphConnector-Test/example/guid.js#L71) are throwing ECPair error and `signGlobalRegistryRecord`[#L75](https://github.com/reTHINK-project/dev-runtime-browser/blob/develop-GraphConnector-Test/example/guid.js#L75) is throwing "TypeError: Cannot read property 'curve' of undefined". 
![image](https://cloud.githubusercontent.com/assets/9600691/15748897/c8d38542-28e0-11e6-953d-e7a846764610.png)

All the tests corresponding to these functions in [runtime_core](https://github.com/reTHINK-project/dev-runtime-core/blob/dev-0.5-GraphConnector/src/graphconnector/GraphConnector.js) are running suucessfully. 
As debugged by @dvilchez earlier, he said that it can be because of uglify step in the gulpfile. 
![image](https://cloud.githubusercontent.com/assets/9600691/15748919/da7aaeec-28e0-11e6-940a-42ba1389a488.png)
So I tried to remove the step but error didn't change instead while bundling process I got other errors
![image](https://cloud.githubusercontent.com/assets/9600691/15748883/b7d9b4aa-28e0-11e6-8910-36193915bf9e.png)
.
Please tell me if this issue is related to "uglify" step in the "gulpfile" and maybe I'm not quite able to disable it properly. But if this issue is not related to "uglify" step then what can be the possible reason for this error.

**Comment by fbeierle** [comment]
I'm getting the same error when trying to remove the uglify step. @dvilchez Do other gulp steps depend on it?

**Comment by dvilchez** [comment]
@fbeierle this error is thrown after remove  uglify step because in an example file there was a wrong dependency. Anyway, since these files don't exist anymore it is not a problem. As I told @ishan210788 I am not sure at 100 % the problem is uglify step but in case it is, your code is bundled with runtime-core not with runtime-browser.

**Comment by fbeierle** [comment]
Using an non-uglified version of runtime-core solves the issue, see https://github.com/reTHINK-project/dev-runtime-core/issues/91
