### ISSUE TITLE
IdP Proxy can't access IdP's domain cookies

### ISSUE THREAD

**Issue by KCorre** [reTHINK-project/dev-runtime-browser#49]
The devlopment of the IdP Proxy/IdModule is subject to the following requirements:
- WebRTC IdP Proxy should be compatible with reThink (so that we follow this standard)

In WebRTC, IdP Proxy sandbox restrictions include that proxies can't open popup to ask user for credentials. This process is done with an error procedure returned to the calling service. When requestion the Id Assertion from the IdP, the IdP Proxy must then rely on cookie authentication to prove that the user as already been authenticated. 

For instance, my code use fetch to retrieve the assertion.

``` javascript
        fetch(_url,myInit)
        .catch(error => {
          console.log(error)
          // We just login but we could do something better maybe?
          // Handling authorizations and such
          var loginURL = SOURCEURL+'/login'
          reject({'name': 'IdPLoginError', 'loginUrl': loginURL})
        })
        .then(response => response.text())
        .then(hash => {
        dump(hash)
          var json = {}
          var data = hash.split('&').toString().split(/[=,]+/);
          for(var i=0; i<data.length; i+=2){
            json[data[i]]=data[i+1];
          }

          resolve({'assertion': json.id_token, 'idp': idp_addr})
```

However, in reThink, this does not work as cookies are not set (which trigger the redirect to /login and then the error IdPLoginError). This is either because 
- Cookies are not visible from the sandbox scope
- Domain of the IdP Proxy is not correctly set, which means that cookies are not visible.

On this last possibility, the domain of the actual IdP is https://energyq.idp.rethink.orange-labs.fr and the IdP Proxy is accessible at https://energyq.idp.rethink.orange-labs.fr/.well-known/idp-proxy/rethink-oidc .
The IdP Proxy MUST be retrieved from the IdP and not hardcoded in to a preset list, contained inside the domain, as one of the requirements (and probably the most important) is the ability to support ANY Identity Provider following user choices. 

My suggestion is thus to first retrieve the IdP Proxy from the expected URL.
- https://energyq.idp.rethink.orange-labs.fr/.well-known/idp-proxy/rethink-oidc 

However, the sandbox may also be a limiting factor and we would like to know if sandbox code can access domain cookies. Could someone working on it gives us an answer? 

This discussion is also active here https://rethink-project.slack.com/messages/dev-identity/ but since there have been no progress, I'm also opening an issue.

**Comment by dvilchez** [comment]
well, it depends on wich sandbox you are referencing. Web worker allows neither access to cookies nor localStorage, but iframe does. The problem with the actual implementation is the same origin policy. The IDP Proxy origin is different from the IDP.

**Comment by Sparika** [comment]
The IDP Proxy origin is not supposed to be different from the IDP's one as it is retrieved from the same domain. If the Proxy was downloaded from the right place (instead of being hardcoded) and instantiated in an invisible iframe, problem would be solved, right?

**Comment by dvilchez** [comment]
Yes, that is.
