### ISSUE TITLE
Uncaught DataCloneError

### ISSUE THREAD

**Issue by dvilchez** [reTHINK-project/dev-runtime-browser#53]
to send messages over postmessage interface is not allowed and causes a new error

**Comment by dvilchez** [comment]
I think this should be move into runtime-core https://rethink-project.slack.com/archives/dev-app/p1467196331000027 @vitormsilva

**Comment by pchainho** [comment]
related with https://github.com/reTHINK-project/dev-runtime-core/issues/97

**Comment by vitormsilva** [comment]
Hi, 
Could someone tell me how I can reproduce this error?
Thank you.
