### ISSUE TITLE
domain://registry.registry/ is tried to be reached when contacting the Global Registry

### ISSUE THREAD

**Issue by fbeierle** [reTHINK-project/dev-runtime-browser#55]
When trying to contact the Global Registry ("global://registry/"), there is a message object created trying to reach "domain://registry.registry/". I guess, the naming scheme makes sense when calling CSPs but not for the Global Registry. Of course "domain://registry.registry/" cannot be reached and the ProtoStubs.json cannot be loaded. See screenshot below.

This used to work, so I think, some recent changes cause this. Can anyone help?

![2016-08-29](https://cloud.githubusercontent.com/assets/10813769/18053366/4a410452-6dff-11e6-984c-c89a62276767.png)

**Comment by pchainho** [comment]
From the Logs it seems something introduced by Policy Engine, @AnaSLCaldeira can you have a look ?

**Comment by AnaSLCaldeira** [comment]
@fbeierle How can I replicate this error?

**Comment by fbeierle** [comment]
Our process is:
- setup hosts

    ```
    127.0.0.1        felix.dev
    192.168.99.100   msg-node.felix.dev
    127.0.0.1        catalogue.felix.dev
    ```

- run docker image of dev-msg-node-vertx
- run ```npm start``` on develop-GraphConnector-Test of dev-runtime-browser
- accept certificate from https://catalogue.felix.dev/
- open https://felix.dev/guid.html, accept certificate
- click on ```queryGlobalRegistry```

**Comment by fbeierle** [comment]
Adding some logging in the MsgBus, we get the following messages, see image below. Looking at the msg flow image here: https://github.com/reTHINK-project/dev-addressbook-app/wiki, it seems to fail at step 10. The MsgBus in the runtime receives the correct response from the MsgNode, but it doesn't reach the GraphConnector, which receives "Response Timeout".

![2016-09-02](https://cloud.githubusercontent.com/assets/10813769/18207982/c6bc8e58-712d-11e6-83e6-b59b97059e03.png)

**Comment by pchainho** [comment]
I see that response message from Global Registry is not compliant with the [specs](https://github.com/reTHINK-project/dev-service-framework/tree/master/docs/datamodel/core/message#responsemessagebody).

**Comment by fbeierle** [comment]
@pchainho : I don't think that can be related to this issue, as the message successfully reaches the message bus and has the right format coming from the Global Registry Connector of the MsgNode (id/type/from/to/body).

@AnaSLCaldeira : Did you look into this issue? Does the Policy Engine maybe call this method: https://github.com/reTHINK-project/dev-runtime-core/blob/develop/src/registry/Registry.js#L167 although it shouldn't in case of contacting the Global Registry?

**Comment by pchainho** [comment]
But the body is not compliant ("code" is missing), and some core components like the Policy Engine could require it

**Comment by AnaSLCaldeira** [comment]
@fbeierle : I was trying to identify the source of the problem, but when I generate a new Runtime descriptor from the master branch of dev-runtime-core and restart your page I get this error:

core.js:294 Uncaught TypeError: Cannot read property 'queryGlobalRegistry' of undefined

How can I update the Runtime descriptor?

**Comment by fbeierle** [comment]
@pchainho : We will change the message body format to be compliant with the specs you linked. @sgoendoer 

@AnaSLCaldeira : The master branch currently does not contain the graph connector in the runtime. Please use the branch https://github.com/reTHINK-project/dev-runtime-core/tree/develop-graphConnector.

**Comment by fbeierle** [comment]
We changed the message body format to be compliant with the linked specs. @AnaSLCaldeira did changes to the Policy Engine for messages regarding the Global Registry.

There still is a problem:
![2016-09-13](https://cloud.githubusercontent.com/assets/10813769/18473806/31163fbc-79bf-11e6-9148-eb0bdf2ea342.png)

We receive the correct response from the Global Registry. However, there seems to appear a second message, "Response timeout!". This issue from April most likely describes the same error: https://github.com/reTHINK-project/dev-runtime-core/issues/82

Anyone got ideas on why we receive the second reply with "Response timeout!"? @reTHINK-project/wp3 

@sgoendoer @ishantiw

**Comment by fbeierle** [comment]
In today's WP4 call, @ingofriese said that @sdruesedow had to introduce some delay in order to be able to establish some connection. I doubt a delay would be the answer here, as the message indicates "Response timeout!". If no one has an answer to this error, we will try to find some workaround.

**Comment by pchainho** [comment]
If this is the same issue as the one you mention we should close this one. I understand you are now able to reach the Global Registry.

The timeout we are experiencing with @sdruesedow is in a cross domain interoperability scenario. In this case it seems that messages sent before the deploy of the "foreign" domain protostub is complete, are being lost. We are studying a fix for this but I don't think your problem is related this one since the protostub was already deployed and a transaction was already performed with it.

Could you provide a new log showing the message.body.value from the response timeout pls?

**Comment by fbeierle** [comment]
I'll close this issue and post the log to the linked issue (https://github.com/reTHINK-project/dev-runtime-core/issues/82).
