### ISSUE TITLE
Browser Persistence Manager is breaking with large amount of data

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-browser#58]
originaly reported at https://github.com/reTHINK-project/dev-runtime-core/issues/119

consider using something else like indexeddb instead of Local storage.

This is killer and should be given priority

**Comment by antonroman** [comment]
Ok, 

then we are reaching 5MB of data stored for persistance, right? 

IndexDB should support more storage, this is going to be the first option to try:

> An application can have a larger quota for persistent storage than temporary storage, but you must request storage using the Quota Management API and the user must grant you permission to use more space. Chrome presents an info bar that prompts the user to grant the app more local storage space.

It is still not clear to us if there is any limit for storage in IndexDB, we are investigating it to make sure.

We are considering another option if we find any issue with indexDB : [https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage]( https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage )

**Comment by dvilchez** [comment]
Unlike LocalStorage IndexedDB exposes an async API this may address to a change on every component using PersistenceManager, is this feasible? @pchainho @vitormsilva

**Comment by pchainho** [comment]
I would prefer not to change the Persistence Manager API.

**Comment by dvilchez** [comment]
Hi @pchainho,

although to expose an async api as a  sync one is possible I have to discourage you from doing it. IndexedDB might be slow to answer and the javascript thread could be blocked for a while.

**Comment by pchainho** [comment]
Then let's move the discussion https://github.com/reTHINK-project/dev-runtime-core/issues/119
