### ISSUE TITLE
StorageManager throws error if no entry exists for given key

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-runtime-browser#61]
In my test, when I request a version of something, e.g. `storageManager.getVersion("someKey").then((result) => {...})`, if there is no entry for `"someKey"`, an error is thrown.

As is common with other databases and the API that was used before storageManager (i.e. persistenceManager), the storageManager should return `undefined` in such a case.

**Comment by dvilchez** [comment]
fixed on 9b27af4491f872de44c7f91f15c1bd6514041a57
