### ISSUE TITLE
runtime/Runtime/version not found

### ISSUE THREAD

**Issue by ishantiw** [reTHINK-project/dev-runtime-browser#62]
We are able to successfully reach Global Registry but on the browser we see protostub error, Please look at the screenshot. I am using [develop-GraphConnector-Test](https://github.com/reTHINK-project/dev-runtime-browser/tree/develop-GraphConnector-Test) branch. Code at [queryGlobalRegistry](https://github.com/reTHINK-project/dev-runtime-browser/blob/develop-GraphConnector-Test/example/guid.js#L318).

![image](https://cloud.githubusercontent.com/assets/9600691/19728915/7d08b402-9b95-11e6-8759-a134f8b9e946.png)
This issue was there earlier and reported in issue #55 . Last time it was resolved by using Runtimes.json file under [descriptor](https://github.com/reTHINK-project/dev-runtime-browser/tree/develop-GraphConnector-Test/example/resources/descriptors) folder which was created as follows:- 
- Using `Runtime.js` file under `dist` folder of dev-runtime-core's `develop-GraphConnector` branch.
- Generating `Runtimes.json` file using `dev-hyperty-toolkit` master branch, using the file from above step.

It was working after the above steps earlier, but recently it has stopped working even if we generate the `Runtimes.json` file from the above steps.  I have tried 'npm update' in `dev-runtime-core` and `dev-runtime-browser` but error is still there.

**Comment by ishantiw** [comment]
As suggested by @pchainho , I merged `develop-GraphConnector` branch of dev-runtime-core with the `develop` branch. I also updated `develop-GraphConnector-Test` of dev-runtime-browser with the master branch. But now I'm trying to run the [addressbook-app](https://github.com/reTHINK-project/dev-addressbook-app/tree/develop) I'm getting below error. 
![image](https://cloud.githubusercontent.com/assets/9600691/19896010/2e9bf244-a053-11e6-9e1d-524d36311e2b.png)
There is no such file https://catalogue.felix.dev/.well-known/runtime/Runtime/version which it is trying to get.

**Comment by fbeierle** [comment]
This issue is blocking our development. It seems like it might have been introduced by changes at the https://github.com/reTHINK-project/dev-service-framework/
To me, it looks like it's just some configuration error. Could please someone look into it and help us here?

@pchainho @dvilchez @sgoendoer @ishantiw @SenanSharhan @reTHINK-project/wp3 @reTHINK-project/wp4

**Comment by pchainho** [comment]
Are you using the Toolkit to test the Graph Connector and the Admin GUI from the Runtime Browser?

Pls ensure that you are using the last versions of the Toolkit develop branch which uses the Runtime Browser.

It is also not clear to me if you are really having an Admin GUI for the Graph Connector running inside the rethink iFrame as discussed [here](https://github.com/reTHINK-project/dev-runtime-core/issues/33#issuecomment-244406689) or something else. Pls see how @gamdias and @AnaSLCaldeira has implemented the [Admin GUI for the Identity Module and the Policy Engine](https://github.com/reTHINK-project/dev-runtime-browser/tree/master/src/admin)
