### ISSUE TITLE
Change from Addressbook App to Admin GUI feasible?

### ISSUE THREAD

**Issue by fbeierle** [reTHINK-project/dev-runtime-browser#64]
So far, no one seems to be able to solve the mystery of the not found runtime (https://github.com/reTHINK-project/dev-runtime-browser/issues/62). @pchainho suggested to change the implementation from how it is done now (see https://github.com/reTHINK-project/dev-addressbook-app/wiki for a description of the interaction of the runtime and the app) to an Admin GUI like it is done for policies and the identity module.

@gamdias and @AnaSLCaldeira: Would such a change be feasible?
1) Can we use HTML? So far the Admin GUIs seem to only be JavaScript (https://github.com/reTHINK-project/dev-runtime-browser/tree/master/src/admin).
2) Can we send messages via the message bus of the runtime?
3) Can the storage manager be accessed? (https://github.com/reTHINK-project/governance-security-implementation/issues/57)
4) What is the development process? It seems like I can access the Admin GUIs in the top right corner when running `npm run start:browser` on dev-hyperty-toolkit branch runtimes. Is this: https://github.com/reTHINK-project/dev-hyperty-toolkit/blob/runtimes/package.json#L25 the place to change which version of the runtime-browser is being used?

@sgoendoer @ishantiw @SenanSharhan

**Comment by gamdias** [comment]
Hello Felix :)

> Can we use HTML? So far the Admin GUIs seem to only be JavaScript (https://github.com/reTHINK-project/dev-runtime-browser/tree/master/src/admin).

yes, in this file you have the html code for the buttons, dropdown, etc. https://github.com/reTHINK-project/dev-runtime-browser/blob/master/bin/index.html

> Can we send messages via the message bus of the runtime?
> Can the storage manager be accessed? (reTHINK-project/governance-security-implementation#57)

yes, all the components can be accessed by the GUI component. Currently the components methods can be invoked directly as seen here: https://github.com/reTHINK-project/dev-runtime-browser/blob/master/src/core.js#L70
But in the future with the shared workers, all communications with the runtime components will be performed using the message bus.

> What is the development process? It seems like I can access the Admin GUIs in the top right corner when running npm run start:browser on dev-hyperty-toolkit branch runtimes. Is this: https://github.com/reTHINK-project/dev-hyperty-toolkit/blob/runtimes/package.json#L25 the place to change which version of the runtime-browser is being used?

To add new GUI's you need to create the GUI javascript file, like the identities GUI https://github.com/reTHINK-project/dev-runtime-browser/tree/master/src/admin, instantiate that class in the core.js ([here](https://github.com/reTHINK-project/dev-runtime-browser/blob/master/src/core.js#L71)), you need to add the new file in the gulp bundle task ([example](https://github.com/reTHINK-project/dev-runtime-browser/blob/master/gulpfile.js#L131)), perform the gulp bundle task. 

To test without committing, you can copy all the files from the runtime-browser /bin folder, and paste it in node_modules/runtime-browser/bin from repository  dev-hyperty-toolkit(branch runtimes), and start the example.

Hope I didn't forget anything. :)

**Comment by pchainho** [comment]
I guess it is clear now that it is feasible. reopen if needed pls
