### ISSUE TITLE
Policy and IDM Admin GUIs: update to use msg bus

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-browser#67]
As agreed [here](https://github.com/reTHINK-project/specs/issues/15)

**Comment by tiagolb** [comment]
The goal is to remove any direct reference to the IDM/Policy by their respective Admin GUIs, right?

![direct1](https://cloud.githubusercontent.com/assets/8178030/22147576/14676524-df01-11e6-86e8-dad75f195c71.png)

Change, for instance, the calls made above to a call by message system.

**Comment by pchainho** [comment]
exactly

**Comment by tiagolb** [comment]
Regarding this issue. I'm in the process of replacing all calls to the IDM in the IdentitiesGUI using the referred model. Once I'm done with the IdentitiesGUI, I'll do the same for the Policy.

Once this modification is made I'm to update the messages used for the IDM [https://github.com/reTHINK-project/specs/blob/master/messages/identity-management-messages.md](here) right? But what about the policy message specification? It must be updated as well right?

**Comment by pchainho** [comment]
yes pls but for the policy management I don't think we have any messages specs yet. You can follow the others spec as a reference

**Comment by tiagolb** [comment]
I have replaced and tested all identity-gui calls to the IDM using the corresponding message types. I'm starting to test the equivalent changes made to the policy-gui.

**Comment by tiagolb** [comment]
This issue is fixed. I have pushed my modifications to two repositories: `dev-runtime-browser:issue67` and `dev-runtime-core:issue67`.

However, there is an error when using the policy gui, particularly when defining a new rule for a policy. When a new rule is defined with the `Subscription preference` filter, this error appears:

![issue67](https://cloud.githubusercontent.com/assets/8178030/23022478/f446a63a-f448-11e6-9886-d3a1fb82a7fa.png)
 

Since this error is not related to this issue (it happened before hand), I'm going to close this issue.

**Comment by dvilchez** [comment]
As we realized yesterday this issue should be opened again. We must decouple AdminGUIs from admin components, that means admin GUIs must not have a dependency with runtime, messagebus or any component running inside the shared worker. I have pushed my changes merged with Tiago's changes in the window_sandbox branch. @tiagolb @pchainho

**Comment by tiagolb** [comment]
Can you please give more information regarding what components I can use to send and receive messages? If I cannot use the messageBus, then what component can be used? Additionally, I believe there are sensitive messages sent between the GUI and Backend components, so the new messaging system must be secure.

**Comment by dvilchez** [comment]
Maybe you can move the admin GUIs to the contextapp and use the contextapp minibus to do this communication. 

Regarding MessageChannel: https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API/Using_channel_messaging
