### ISSUE TITLE
Login popup does not not open with Firefox

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-browser#68]
![image](https://cloud.githubusercontent.com/assets/3893553/20708674/040e11a6-b629-11e6-9820-fd898027d0d6.png)

**Comment by dvilchez** [comment]
The error was related to don't pass the event as an argument after solved it, it is still failing

this call to identity module https://github.com/reTHINK-project/dev-runtime-browser/blob/master/src/admin/IdentitiesGUI.js#L215

    _this.identityModule.crypto.generateRSAKeyPair()

throws

    SyntaxError: "An invalid or illegal string was specified"

**Comment by pchainho** [comment]
@tiagolb can you have a look here, pls?

**Comment by sdruesedow** [comment]
I created a pull request that fixes this issue for me. Please have a look and check: https://github.com/reTHINK-project/dev-runtime-browser/pull/69
