### ISSUE TITLE
Update with Runtime Dev-Interworking

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-browser#70]
At least the following has to be done:

- [x] requireHyperty(): add new optional parameter `reuseAddress` -> check runtimeUA.loadHyperty(..) new attribute that is used to set if Hyperty addresses are to be reused .
- [x] create sandboxes according to runtime capabilities. -> have a look [here](https://github.com/reTHINK-project/dev-hyperty-toolkit/tree/dev-p2p/resources/factories)
- [x] windowSandbox support

**Comment by dvilchez** [comment]
sorry @pchainho, could you provide more info about this issue?

**Comment by pchainho** [comment]
I've provided more info.

**Comment by dvilchez** [comment]
>create sandboxes according to runtime capabilities. -> have a look here

runtime-browser doesn't create the sanboxes

>windowSandbox support

what does it mean?

**Comment by dvilchez** [comment]
From slack:

pchainho [4:13 PM] 
@dvilchez regarding your comment in the issue

[4:14]  
> runtime-browser doesn't create the sanboxes

[4:14]  
sandbox implementations are specific to the runtime types (edited)

[4:15]  
the decision about which sandbox implementation to be used should not be from the runtime core

dvilchez [4:17 PM] 
?

[4:18]  
until now we had appsandbox and worker sandbox

[4:18]  
and the runtime created them

[4:20]  
do you want to move this responsibility to the browser?

[4:20]  
or only one part of it

[4:21]  
as I asked you. I need you provide more info

pchainho [4:24 PM] 
yes, according to the constraints provided in the descriptors of the different components to be deployed, the decision about the right sandbox that can fulfill such constraints, should be taken where you have info about how the sandbox is implemented and capabilities supported (edited)

dvilchez [4:27 PM] 
and what is the interface the runtime browser has to expose to the runtime?

pchainho [4:27 PM] 
eg a protostub requiring WebRTC API would use the windowSandbox in the Browser Runtime but in the nodeJS runtime it would be something else

[4:28]  
I think there is a proposal in the dev-p2p toolkit branch

[4:28]  
runtimeFactory if not wrong
